import './globals.css'
import { UserProvider } from '@/context/UserContext'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='root-layout'>
          <UserProvider>
            {children}
          </UserProvider>
        </div>
      </body>
    </html>
  )
}
